# Generated by Django 3.1.7 on 2021-02-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name_plural': 'Citie'},
        ),
        migrations.AddField(
            model_name='city',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='temperature',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
