# Generated by Django 3.1.7 on 2021-02-23 06:39

from django.db import migrations, models
import mapbox_location_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_auto_20210221_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', mapbox_location_field.models.LocationField(blank=True, map_attrs={'center': (17.031645, 51.106715), 'style': 'mapbox://styles/mightysharky/cjwgnjzr004bu1dnpw8kzxa72'}, null=True)),
                ('address', mapbox_location_field.models.AddressAutoHiddenField(blank=True, map_id='map', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='city',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='temperature',
            field=models.CharField(max_length=25),
        ),
    ]
