# Generated by Django 3.1.7 on 2021-02-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_auto_20210223_1226'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weather_api', models.CharField(max_length=400)),
                ('map_api', models.CharField(max_length=400)),
            ],
        ),
    ]
